name: Update Agenda

on:
  schedule:
    - cron: "0 7 * * *"

  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: node index.js
        env:
          FRAMER_API_KEY: ${{ secrets.FRAMER_API_KEY }}